# Makefile — single entry point for dev/test commands.
#
# Target NAMES are the stable contract referenced by CLAUDE.md; the recipe
# internals below wrap whatever works in this repo today (host venv + the dev
# docker-compose stack). They are expected to be swapped later for a dedicated
# docker/docker-compose.test.yml WITHOUT changing these target names.
#
# Prereqs today: backend/.venv (pip install -e "backend[dev]"), frontend/node_modules
# (npm ci), a filled .env, and Docker running.

COMPOSE_FILE := docker/docker-compose.yml
# Prefer Compose v2 (`docker compose`); fall back to v1 (`docker-compose`).
DC := $(shell docker compose version >/dev/null 2>&1 && echo "docker compose" || echo "docker-compose")
# Put the backend venv on PATH so the tools AND alembic's post-write hook (ruff) resolve.
VENVBIN := $(CURDIR)/backend/.venv/bin
BE := cd backend && export PATH="$(VENVBIN):$$PATH" &&

.PHONY: help test test-backend test-frontend lint migrate-test migration up-test down-test

help:
	@echo "Targets:"
	@echo "  test           - backend + frontend checks"
	@echo "  test-backend   - pytest (needs up-test running)"
	@echo "  test-frontend  - tsc typecheck (no vitest suite yet)"
	@echo "  lint           - ruff + mypy (backend) + tsc (frontend)"
	@echo "  migrate-test   - alembic upgrade head"
	@echo "  migration m=\"...\" - new autogenerated migration"
	@echo "  up-test        - start postgres/redis/minio"
	@echo "  down-test      - stop postgres/redis/minio"

# --- test env (stateful services) ---
up-test:
	$(DC) -f $(COMPOSE_FILE) --env-file .env up -d

down-test:
	$(DC) -f $(COMPOSE_FILE) --env-file .env down

# --- migrations ---
migrate-test:
	$(BE) alembic upgrade head

migration:
	@test -n "$(m)" || { echo 'usage: make migration m="<name>"'; exit 1; }
	$(BE) alembic revision --autogenerate -m "$(m)"

# --- tests ---
test: test-backend test-frontend

test-backend:
	$(BE) pytest -q

# No vitest suite yet — typecheck is the frontend gate (see CLAUDE.md testing rules).
test-frontend:
	cd frontend && npm run typecheck

# --- lint + typecheck ---
lint:
	$(BE) ruff check app alembic && mypy app
	cd frontend && npm run typecheck
