# Makefile — single entry point for test commands.
#
# Target NAMES are the stable contract referenced by CLAUDE.md. Internals wrap
# the dedicated test stack (docker-compose.test.yaml): postgres/redis/minio +
# a one-off `api` container built from the prod Dockerfile. All Python tooling
# runs INSIDE that container (service-name networking, .env.test), so nothing
# depends on a host venv. Frontend checks run in a throwaway node container.
#
# Prereqs: Docker running. Nothing else — no host venv, no host node_modules.

COMPOSE_FILE := docker/docker-compose.test.yaml
PROJECT := argonautica-test
# Prefer Compose v2 (`docker compose`); fall back to v1 (`docker-compose`).
DC := $(shell docker compose version >/dev/null 2>&1 && echo "docker compose" || echo "docker-compose")
DCT := $(DC) -p $(PROJECT) -f $(COMPOSE_FILE)
# Node image pinned to the frontend build image (frontend/Dockerfile).
NODE_IMAGE := node:20-slim
# Frontend check in a throwaway container; node_modules in an anon volume so the
# install never writes root-owned files back onto the host tree.
FE_RUN := docker run --rm -v "$(CURDIR)/frontend":/app -v /app/node_modules -w /app $(NODE_IMAGE)

# --- local prod-like stack (browser/Playwright checks before commit) ---
# Runs the ACTUAL docker/docker-compose.prod.yml locally (DOMAIN=localhost,
# MEDIA_DOMAIN=media.localhost from .env) — same topology as prod: one nginx
# edge, built SPA, MinIO behind it. No blue-green (single backend-blue),
# bot always scaled to 0 (needs a real TELEGRAM_BOT_TOKEN). Separate project
# name (platform-local) so it never collides with the test stack or prod.
LOCAL_CF := docker/docker-compose.prod.yml
LOCAL_PROJECT := platform-local
LOCAL_DCT := $(DC) -p $(LOCAL_PROJECT) -f $(LOCAL_CF) --env-file .env

.PHONY: help test test-backend test-frontend lint migrate-test migration up-test down-test local-up local-down local-reset local-logs

help:
	@echo "Targets:"
	@echo "  up-test        - start postgres/redis/minio (waits until ready)"
	@echo "  down-test      - stop the stack and drop volumes"
	@echo "  migrate-test   - alembic upgrade head (in the api container)"
	@echo "  migration m=\"...\" - new autogenerated migration"
	@echo "  test           - backend (pytest) + frontend (tsc) checks"
	@echo "  test-backend   - pytest in the api container"
	@echo "  test-frontend  - tsc typecheck in a node container (no vitest yet)"
	@echo "  lint           - ruff + mypy (backend) + tsc (frontend)"
	@echo "  local-up       - build + migrate + start prod-like stack at https://localhost"
	@echo "  local-down     - stop it (data kept)"
	@echo "  local-reset    - stop it + drop volumes (clean DB/MinIO)"
	@echo "  local-logs     - tail backend + nginx logs"

# --- test env (stateful services) ---
up-test:
	$(DCT) up -d postgres redis minio
	@echo "waiting for postgres/redis..."
	@for i in $$(seq 1 30); do \
		$(DCT) exec -T postgres pg_isready -U argo_test -d argo_test >/dev/null 2>&1 \
		&& $(DCT) exec -T redis redis-cli ping >/dev/null 2>&1 \
		&& { echo "ready"; exit 0; }; \
		sleep 1; \
	done; echo "services did not become ready in time" >&2; exit 1

down-test:
	$(DCT) down -v

# --- migrations (in the api container) ---
migrate-test:
	$(DCT) run --rm api alembic upgrade head

migration:
	@test -n "$(m)" || { echo 'usage: make migration m="<name>"'; exit 1; }
	# Run as the host user so the generated file lands host-owned (bind mount),
	# not root-owned. ruff post-write hook is baked into the test image.
	$(DCT) run --rm -u "$$(id -u):$$(id -g)" api \
		alembic revision --autogenerate -m "$(m)"

# --- tests ---
# Dev tooling (pytest/ruff/mypy) is baked into the image's `test` stage — no
# network installs at run time. See backend/requirements-dev.txt.
test: test-backend test-frontend

test-backend:
	$(DCT) run --rm api pytest -q -p no:cacheprovider

# No vitest suite yet — typecheck is the frontend gate (see CLAUDE.md testing rules).
test-frontend:
	$(FE_RUN) sh -lc "npm ci --silent && npm run typecheck"

# --- lint + typecheck ---
# Caches redirected off the read-only bind mount so lint runs as the image user.
lint:
	$(DCT) run --rm api sh -lc "ruff check --no-cache app alembic && mypy --cache-dir=/tmp/mypy app"
	$(FE_RUN) sh -lc "npm ci --silent && npm run typecheck"

# --- local prod-like stack ---
# First run needs TLS certs trusted by the browser (mkcert, one-time, see CLAUDE.md):
#   mkcert -install
#   mkcert -cert-file docker/nginx/certs/localhost.crt -key-file docker/nginx/certs/localhost.key localhost 127.0.0.1 ::1
#   mkcert -cert-file docker/nginx/certs/media.localhost.crt -key-file docker/nginx/certs/media.localhost.key media.localhost
local-up:
	@test -f docker/nginx/certs/localhost.crt || \
		{ echo "нет docker/nginx/certs/*.crt — см. коммент над local-up в Makefile (mkcert)"; exit 1; }
	$(LOCAL_DCT) build backend-blue frontend
	$(LOCAL_DCT) run --rm migrate
	$(LOCAL_DCT) up -d postgres redis minio backend-blue transcode-worker frontend nginx
	@echo "waiting for backend..."
	@for i in $$(seq 1 30); do $(LOCAL_DCT) exec -T backend-blue true >/dev/null 2>&1 && break; sleep 1; done
	@$(LOCAL_DCT) exec -T backend-blue python -m scripts.bootstrap_admin admin
	@echo "https://localhost  (admin / see password above on first run)"

local-down:
	$(LOCAL_DCT) stop

local-reset:
	$(LOCAL_DCT) down -v

local-logs:
	$(LOCAL_DCT) logs -f backend-blue nginx
