"""users auth fields

Revision ID: d8305ec631e1
Revises: 799c88b82d58
Create Date: 2026-06-29 04:21:06.922897

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8305ec631e1'
down_revision: str | None = '799c88b82d58'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # username добавляем безопасным порядком (expand/contract, CLAUDE.md п.8):
    # nullable -> UNIQUE -> SET NOT NULL. На пустой таблице бэкфилл не нужен, но
    # разнесение шагов снимает риск NOT-NULL-on-add при наличии строк.
    op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    op.alter_column('users', 'username', existing_type=sa.Text(), nullable=False)

    op.add_column(
        'users',
        sa.Column(
            'must_change_password',
            sa.Boolean(),
            server_default='false',
            nullable=False,
        ),
    )
    # email становится опциональным (логин теперь по username) — ослабление, обратносовместимо.
    op.alter_column('users', 'email', existing_type=sa.TEXT(), nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
