"""intake funnel timestamps

Revision ID: 9e747d7af6f6
Revises: b93a1ac79274
Create Date: 2026-08-26 20:22:38.459645

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e747d7af6f6'
down_revision: str | None = 'c1a7d3f95b48'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake_applications', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('intake_applications', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('intake_applications', sa.Column('plan_chosen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('intake_applications', sa.Column('receipt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('intake_applications', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_intake_applications_created_at', 'intake_applications', ['created_at'], unique=False)
    op.create_index('ix_intake_applications_status', 'intake_applications', ['status'], unique=False)
    # NB: autogenerate also re-reports drops of ix_journal_credits_user_id,
    # ix_journal_pardons_user_id, ix_journal_sections_program_id, uq_rooms_news_per_intake
    # and notifications.task_id — phantom diffs, see docs/DATA_MODEL.md "Migrations gotchas".
    # Deliberately not included here.

    # Backfill (ARG-107): confirmed_at is exact — a platform user is created exactly at
    # the moment payment is confirmed. submitted_at is an approximation for historical
    # rows (the /start -> about text step almost always happens in one sitting).
    op.execute(
        """
        UPDATE intake_applications AS a
        SET confirmed_at = u.created_at
        FROM users AS u
        WHERE a.user_id = u.id AND a.status = 'confirmed'
        """
    )
    op.execute(
        """
        UPDATE intake_applications
        SET submitted_at = created_at
        WHERE status != 'awaiting_about'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intake_applications_status', table_name='intake_applications')
    op.drop_index('ix_intake_applications_created_at', table_name='intake_applications')
    op.drop_column('intake_applications', 'confirmed_at')
    op.drop_column('intake_applications', 'receipt_at')
    op.drop_column('intake_applications', 'plan_chosen_at')
    op.drop_column('intake_applications', 'accepted_at')
    op.drop_column('intake_applications', 'submitted_at')
    # ### end Alembic commands ###
