"""add user intake access

Revision ID: cc783668e322
Revises: c61f3cac42f8
Create Date: 2026-09-05 02:30:51.033964

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc783668e322'
down_revision: str | None = 'c61f3cac42f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_intake_access',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('intake_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], name=op.f('fk_user_intake_access_intake_id_intakes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_intake_access_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'intake_id', name=op.f('pk_user_intake_access'))
    )
    op.create_index('ix_user_intake_access_intake', 'user_intake_access', ['intake_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also emitted the 4 documented phantom index drops
    # (uq_rooms_news_per_intake, ix_journal_{credits,pardons}_user_id,
    # ix_journal_sections_program_id — see docs/DATA_MODEL.md "Migrations
    # gotchas") plus two unrelated legacy-column drops (calendar_events.room_id,
    # notifications.task_id, both kept physically on purpose per docs) —
    # stripped, not real changes for this migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_intake_access_intake', table_name='user_intake_access')
    op.drop_table('user_intake_access')
    # ### end Alembic commands ###
