"""add playlist attachments

Revision ID: b7c426100236
Revises: a3c9f1e7b2d4
Create Date: 2026-09-18 07:45:12.267447

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7c426100236'
down_revision: str | None = 'a3c9f1e7b2d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # NOTE: autogenerate also re-reported four unrelated phantom index diffs
    # (uq_rooms_news_per_intake / ix_journal_pardons_user_id /
    # ix_journal_credits_user_id / ix_journal_sections_program_id) plus other
    # pre-existing drift unrelated to playlists (calendar_events.room_id,
    # notifications.task_id, ix_tasks_publish_at) — stripped per docs/DATA_MODEL.md
    # "Migrations gotchas". Only the playlist changes are kept below.
    op.create_table('playlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('cover_media_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media_assets.id'], name=op.f('fk_playlists_cover_media_id_media_assets')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_playlists_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists'))
    )
    op.create_table('playlist_tracks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('media_asset_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('artist', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_playlist_tracks_media_asset_id_media_assets')),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_tracks_playlist_id_playlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlist_tracks')),
    sa.UniqueConstraint('playlist_id', 'position', name='uq_playlist_tracks_position')
    )
    op.add_column('kb_items', sa.Column('playlist_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_kb_items_playlist_id_playlists'), 'kb_items', 'playlists', ['playlist_id'], ['id'])
    op.add_column('messages', sa.Column('playlist_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_messages_playlist_id_playlists'), 'messages', 'playlists', ['playlist_id'], ['id'])
    op.add_column('tasks', sa.Column('playlist_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_playlist_id_playlists'), 'tasks', 'playlists', ['playlist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_playlist_id_playlists'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'playlist_id')
    op.drop_constraint(op.f('fk_messages_playlist_id_playlists'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'playlist_id')
    op.drop_constraint(op.f('fk_kb_items_playlist_id_playlists'), 'kb_items', type_='foreignkey')
    op.drop_column('kb_items', 'playlist_id')
    op.drop_table('playlist_tracks')
    op.drop_table('playlists')
    # ### end Alembic commands ###
