"""stream tasks

Revision ID: ece6436b7ff4
Revises: 890c84f56ca7
Create Date: 2026-07-19 06:57:53.261729

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ece6436b7ff4'
down_revision: str | None = '890c84f56ca7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_stream_texts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_stream_texts_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_stream_texts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_stream_texts')),
    sa.UniqueConstraint('task_id', 'user_id', 'version', name='uq_task_stream_text')
    )
    op.create_table('task_streams',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_streams_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_streams')),
    sa.UniqueConstraint('task_id', name='uq_task_stream_task')
    )
    op.create_table('task_stream_nodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('side', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('phrase', sa.Text(), nullable=True),
    sa.Column('phrase_option_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("side IN ('left', 'right')", name=op.f('ck_task_stream_nodes_task_stream_node_side_valid')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_task_stream_nodes_approved_by_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['task_stream_nodes.id'], name=op.f('fk_task_stream_nodes_parent_id_task_stream_nodes')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_task_stream_nodes_room_id_rooms')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_stream_nodes_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_stream_nodes'))
    )
    op.create_index('ix_task_stream_nodes_room', 'task_stream_nodes', ['room_id'], unique=False)
    op.create_index('ix_task_stream_nodes_task', 'task_stream_nodes', ['task_id'], unique=False)
    op.create_table('task_stream_node_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['task_stream_nodes.id'], name=op.f('fk_task_stream_node_members_node_id_task_stream_nodes')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_stream_node_members_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_stream_node_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_stream_node_members')),
    sa.UniqueConstraint('node_id', 'user_id', name='uq_task_stream_node_member')
    )
    op.create_index('ix_task_stream_node_members_user', 'task_stream_node_members', ['task_id', 'user_id'], unique=False)
    op.create_table('task_stream_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_task_stream_options_author_id_users')),
    sa.ForeignKeyConstraint(['node_id'], ['task_stream_nodes.id'], name=op.f('fk_task_stream_options_node_id_task_stream_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_stream_options'))
    )
    op.create_index('ix_task_stream_options_node', 'task_stream_options', ['node_id'], unique=False)
    op.create_table('task_stream_votes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['task_stream_nodes.id'], name=op.f('fk_task_stream_votes_node_id_task_stream_nodes')),
    sa.ForeignKeyConstraint(['option_id'], ['task_stream_options.id'], name=op.f('fk_task_stream_votes_option_id_task_stream_options')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_stream_votes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_stream_votes')),
    sa.UniqueConstraint('node_id', 'user_id', name='uq_task_stream_vote')
    )
    # NOTE: phantom index drops removed (see docs/DATA_MODEL.md "Migrations gotchas").
    # ### end Alembic commands ###
    # Расширить допустимые значения tasks.type: добавить 'stream' (поток).
    # CheckConstraint autogenerate не диффит — правим вручную. Имена — «голые»
    # (без ck_tasks_-префикса): его добавляет naming_convention метаданных.
    op.drop_constraint('task_type_valid', 'tasks', type_='check')
    op.create_check_constraint(
        'task_type_valid', 'tasks',
        "type IN ('common', 'individual', 'pair', 'stream')",
    )


def downgrade() -> None:
    op.drop_constraint('task_type_valid', 'tasks', type_='check')
    op.create_check_constraint(
        'task_type_valid', 'tasks', "type IN ('common', 'individual', 'pair')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_stream_votes')
    op.drop_index('ix_task_stream_options_node', table_name='task_stream_options')
    op.drop_table('task_stream_options')
    op.drop_index('ix_task_stream_node_members_user', table_name='task_stream_node_members')
    op.drop_table('task_stream_node_members')
    op.drop_index('ix_task_stream_nodes_task', table_name='task_stream_nodes')
    op.drop_index('ix_task_stream_nodes_room', table_name='task_stream_nodes')
    op.drop_table('task_stream_nodes')
    op.drop_table('task_streams')
    op.drop_table('task_stream_texts')
    # ### end Alembic commands ###
