"""torch_posts

Revision ID: 6a25457918ee
Revises: bc08d5154d7d
Create Date: 2026-09-28 10:48:22.144920

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a25457918ee'
down_revision: str | None = 'bc08d5154d7d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torch_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_torch_posts_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_torch_posts'))
    )
    op.create_index('ix_torch_posts_author_created', 'torch_posts', ['author_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping calendar_events.room_id and three
    # partial indexes (uq_rooms_torch_singleton, ix_tasks_publish_at, plus the
    # three documented phantom journal_*/rooms indexes) — pre-existing drift
    # unrelated to this task (see docs/DATA_MODEL.md "Migrations gotchas").
    # Deliberately stripped, not committed.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_torch_posts_author_created', table_name='torch_posts')
    op.drop_table('torch_posts')
    # ### end Alembic commands ###
