"""pair tasks

Revision ID: a5ac607d6dee
Revises: d814776cf50d
Create Date: 2026-07-12 21:44:37.314522

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5ac607d6dee'
down_revision: str | None = 'd814776cf50d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_pairs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('meeting_organizer_id', sa.BigInteger(), nullable=False),
    sa.Column('meeting_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_organizer_id'], ['users.id'], name=op.f('fk_task_pairs_meeting_organizer_id_users')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_pairs_task_id_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_pairs'))
    )
    op.create_index('ix_task_pairs_task', 'task_pairs', ['task_id'], unique=False)
    op.create_table('task_pair_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['task_pairs.id'], name=op.f('fk_task_pair_members_pair_id_task_pairs')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_pair_members_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_pair_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_pair_members')),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_pair_member')
    )
    op.create_index('ix_task_pair_members_pair', 'task_pair_members', ['pair_id'], unique=False)
    # NOTE: phantom index drops removed (see docs/DATA_MODEL.md "Migrations gotchas").
    op.add_column('tasks', sa.Column('pair_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_pair_id_task_pairs'), 'tasks', 'task_pairs', ['pair_id'], ['id'])
    # ### end Alembic commands ###
    # Расширить допустимые значения tasks.type: добавить 'pair' (взаимное обучение).
    # CheckConstraint autogenerate не диффит — правим вручную. Имена — «голые»
    # (без ck_tasks_-префикса): его добавляет naming_convention метаданных.
    op.drop_constraint('task_type_valid', 'tasks', type_='check')
    op.create_check_constraint(
        'task_type_valid', 'tasks', "type IN ('common', 'individual', 'pair')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_type_valid', 'tasks', type_='check')
    op.create_check_constraint(
        'task_type_valid', 'tasks', "type IN ('common', 'individual')"
    )
    op.drop_constraint(op.f('fk_tasks_pair_id_task_pairs'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'pair_id')
    op.drop_index('ix_task_pair_members_pair', table_name='task_pair_members')
    op.drop_table('task_pair_members')
    op.drop_index('ix_task_pairs_task', table_name='task_pairs')
    op.drop_table('task_pairs')
    # ### end Alembic commands ###
