"""avatar and sticker media refs

Revision ID: e10ce43ba1d3
Revises: fb716285fe92
Create Date: 2026-06-30 08:53:53.293129

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e10ce43ba1d3'
down_revision: str | None = 'fb716285fe92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stickers', sa.Column('image_media_id', sa.BigInteger(), nullable=True))
    op.alter_column('stickers', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(op.f('fk_stickers_image_media_id_media_assets'), 'stickers', 'media_assets', ['image_media_id'], ['id'])
    op.add_column('users', sa.Column('avatar_media_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_users_avatar_media_id_media_assets'), 'users', 'media_assets', ['avatar_media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_avatar_media_id_media_assets'), 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_media_id')
    op.drop_constraint(op.f('fk_stickers_image_media_id_media_assets'), 'stickers', type_='foreignkey')
    op.alter_column('stickers', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('stickers', 'image_media_id')
    # ### end Alembic commands ###
