"""initial schema

Revision ID: 799c88b82d58
Revises: 
Create Date: 2026-06-28 23:44:13.704730

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '799c88b82d58'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_categories'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='participant', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('participant', 'admin')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('kb_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['kb_categories.id'], name=op.f('fk_kb_items_category_id_kb_categories')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_kb_items_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_items'))
    )
    op.create_table('media_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('image', 'video', 'file')", name=op.f('ck_media_assets_kind_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_media_assets_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    op.create_table('rooms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('dm_key', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('dm', 'group', 'channel')", name=op.f('ck_rooms_type_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_rooms_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms')),
    sa.UniqueConstraint('dm_key', name=op.f('uq_rooms_dm_key'))
    )
    op.create_table('stickerpacks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stickerpacks_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stickerpacks'))
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_calendar_events_created_by_users')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_calendar_events_room_id_rooms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events'))
    )
    op.create_table('kb_item_media',
    sa.Column('kb_item_id', sa.BigInteger(), nullable=False),
    sa.Column('media_asset_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['kb_item_id'], ['kb_items.id'], name=op.f('fk_kb_item_media_kb_item_id_kb_items')),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_kb_item_media_media_asset_id_media_assets')),
    sa.PrimaryKeyConstraint('kb_item_id', 'media_asset_id', name=op.f('pk_kb_item_media'))
    )
    op.create_table('stickers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pack_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['stickerpacks.id'], name=op.f('fk_stickers_pack_id_stickerpacks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stickers'))
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('thread_root_id', sa.BigInteger(), nullable=True),
    sa.Column('sticker_id', sa.BigInteger(), nullable=True),
    sa.Column('reply_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_messages_room_id_rooms')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.ForeignKeyConstraint(['sticker_id'], ['stickers.id'], name=op.f('fk_messages_sticker_id_stickers')),
    sa.ForeignKeyConstraint(['thread_root_id'], ['messages.id'], name=op.f('fk_messages_thread_root_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_room_thread_created', 'messages', ['room_id', 'thread_root_id', 'created_at'], unique=False)
    op.create_table('message_attachments',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('media_asset_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], name=op.f('fk_message_attachments_media_asset_id_media_assets')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_attachments_message_id_messages')),
    sa.PrimaryKeyConstraint('message_id', 'media_asset_id', name=op.f('pk_message_attachments'))
    )
    op.create_table('pinned_messages',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('pinned_by', sa.BigInteger(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_pinned_messages_message_id_messages')),
    sa.ForeignKeyConstraint(['pinned_by'], ['users.id'], name=op.f('fk_pinned_messages_pinned_by_users')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_pinned_messages_room_id_rooms')),
    sa.PrimaryKeyConstraint('room_id', 'message_id', name=op.f('pk_pinned_messages'))
    )
    op.create_table('room_members',
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_in_room', sa.Text(), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_message_id', sa.BigInteger(), nullable=True),
    sa.Column('is_muted', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("role_in_room IN ('owner', 'member')", name=op.f('ck_room_members_role_in_room_valid')),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], name=op.f('fk_room_members_last_read_message_id_messages')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_members_room_id_rooms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_room_members_user_id_users')),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_members')
    op.drop_table('pinned_messages')
    op.drop_table('message_attachments')
    op.drop_index('ix_messages_room_thread_created', table_name='messages')
    op.drop_table('messages')
    op.drop_table('stickers')
    op.drop_table('kb_item_media')
    op.drop_table('calendar_events')
    op.drop_table('stickerpacks')
    op.drop_table('rooms')
    op.drop_table('media_assets')
    op.drop_table('kb_items')
    op.drop_table('users')
    op.drop_table('kb_categories')
    # ### end Alembic commands ###
