"""users can_create_groups

Revision ID: fb716285fe92
Revises: d8305ec631e1
Create Date: 2026-06-29 05:27:52.681322

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fb716285fe92'
down_revision: str | None = 'd8305ec631e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_create_groups', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_create_groups')
    # ### end Alembic commands ###
